#!/usr/bin/env bash

main() {
  local lock_img="$1"
  local snapshot_cmd="$2"
  local down_scale_factor="$3"
  local up_scale_factor="$4"

  cleanup() {
    rm -f "$lock_img"
  }

  trap cleanup EXIT

  check_dependencies() {
    local dependencies=("maim" "magick" "i3lock" "dunstctl")
    local missing_dependencies=()

    for dep in "${dependencies[@]}"; do
      if ! command -v "$dep" >/dev/null; then
        missing_dependencies+=("$dep")
      fi
    done

    if [[ ${#missing_dependencies[@]} -gt 0 ]]; then
      echo "Missing dependencies: ${missing_dependencies[*]}" >&2
      exit 1
    fi
  }

  check_dependencies

  # Pause Dunst notifications
  dunstctl set-paused true
  amixer set Master mute

  $snapshot_cmd
  magick "$lock_img" -scale "$down_scale_factor" -scale "$up_scale_factor" "$lock_img"

  # Lock the screen
  i3lock -i "$lock_img"

  # Wait for i3lock to exit
  while pgrep -x i3lock >/dev/null; do
    sleep 1
  done

  # Resume Dunst notifications
  dunstctl set-paused false
  amixer set Master unmute

  rm "$lock_img"
}

# Define the variables
LOCK_IMG=/tmp/lock.png
SNAPSHOT_CMD="maim $LOCK_IMG"
DOWN_SCALE_FACTOR="10%"
UP_SCALE_FACTOR="1000%"

# Call the main function with the necessary variables
main "$LOCK_IMG" "$SNAPSHOT_CMD" "$DOWN_SCALE_FACTOR" "$UP_SCALE_FACTOR"
