#!/bin/sh

# add more args here according to preference
ARGS="--volume=80"
theme=$(cat "$HOME/.config/i3/.theme")

notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "Playing now: " "$@" --icon=media-tape
}

menu() {
	printf "1. Lofi Girl\n"
	printf "2. Chillhop\n"
	printf "3. Box Lofi\n"
	printf "4. The Bootleg Boy\n"
	printf "5. Radio Spinner\n"
	printf "6. SmoothChill"
}

main() {
    local launcher_file="$HOME/.config/i3/polybar/themes/$theme/rofi/launcher.rasi"

    local choice
    if [[ -f "$launcher_file" ]]; then
        choice=$(menu | rofi -theme "$launcher_file" -dmenu | cut -d. -f1)
    else
        choice=$(menu | rofi -dmenu | cut -d. -f1)
    fi

    if [ -z "$choice" ]; then
        exit 0
    fi

	case $choice in
		1)
			notification "Lofi Girl ☕️ 🎶";
            URL="https://play.streamafrica.net/lofiradio"
			;;
		2)
			notification "Chillhop ☕️ 🎶";
            URL="http://stream.zeno.fm/fyn8eh3h5f8uv"
			;;
		3)
			notification "Box Lofi ☕️ 🎶";
            URL="http://stream.zeno.fm/f3wvbbqmdg8uv"
			;;
		4)
			notification "The Bootleg Boy ☕️ 🎶";
            URL="http://stream.zeno.fm/0r0xa792kwzuv"
			;;
		5)
			notification "Radio Spinner ☕️ 🎶";
            URL="https://live.radiospinner.com/lofi-hip-hop-96"
			;;
		6)
			notification "SmoothChill ☕️ 🎶";
            URL="https://media-ssl.musicradio.com/SmoothChill"
			;;
		7)
			notification "SmoothJazz ☕️ 🎶";
            URL="https://live.radiospinner.com/smooth-vocal-jazz-96"
			;;
	esac

    if [ -n "$URL" ]; then
        # run mpv with args and selected url
        # added title arg to make sure the pkill command kills only this instance of mpv
        mpv $ARGS --title="radio-mpv" $URL
    fi
}

pkill -f radio-mpv || main
