#!/usr/bin/env bash

########################
# Original: gh0stzk    #
# Modified: Cadehlinha #
########################

timestamp=$(date +%d_%m_%Y-%I-%M-%S)
dir="$(xdg-user-dir PICTURES)/ScreenShots"
filename="$dir/Screenshot-${timestamp}.png"

[ -d "$dir" ] || mkdir -p "$dir"

# Function to show a notification with dunst
show_notification() {
    dunstify --replace=699 -i "$1" "Screenshot" "$2"
}

countdown() {
	for sec in $(seq "$1" -1 1); do
		dunstify -t 1000 --replace=699 "Taking shot in : $sec"
		sleep 1
	done
}

take_screenshot() {
    scrot "$filename"
    xclip -selection clipboard -t image/png -i "$filename"
    show_notification "$filename" "$1"
}

case $1 in
	--now)
		take_screenshot "Screenshot saved and copied to clipboard";;
	--in5)
		countdown 5
		take_screenshot "Scheduled capture taken after 10 seconds and copied to clipboard";;
	--sel)
        sleep 0.5
		scrot -s "$filename"
		xclip -selection clipboard -t image/png -i "$filename"
		show_notification "$filename" "Screenshot of selected area saved and copied to clipboard";;
	--active)
		scrot -u -e "xdotool getactivewindow" "$filename"
		xclip -selection clipboard -t image/png -i "$filename"
		show_notification "$filename" "Screenshot of active window saved and copied to clipboard";;
	*)
		take_screenshot "Screenshot saved and copied to clipboard";;
esac
